SELECT P.PRODUCT_ID,
(CASE WHEN US.PRODUCT_ID IS NULL THEN  0 ELSE ROUND(SUM(P.PRICE*US.UNITS)/SUM(US.UNITS),2) END )AS AVERAGE_PRICE
FROM PRICES AS P
LEFT JOIN UNITSSOLD AS US
ON P.PRODUCT_ID=US.PRODUCT_ID OR US.PRODUCT_ID IS NULL
WHERE (US.PURCHASE_DATE>=P.START_DATE AND US.PURCHASE_DATE<=P.END_DATE) OR US.PRODUCT_ID IS NULL
GROUP BY P.PRODUCT_ID
