# Write your MySQL query statement below
SELECT QUERY_NAME,
ROUND(SUM(RATING/POSITION)/COUNT(*),2) AS QUALITY,
ROUND((SUM(CASE WHEN RATING <3 THEN 1 ELSE 0 END)*100/COUNT(*)),2) AS POOR_QUERY_PERCENTAGE
FROM QUERIES
GROUP BY QUERY_NAME