# Write your MySQL query statement below
# SELECT T.CUSTOMER_NUMBER FROM 
# (SELECT CUSTOMER_NUMBER,COUNT(*) AS COUNT 
# FROM ORDERS
# GROUP BY CUSTOMER_NUMBER
# ORDER BY COUNT DESC) AS T LIMIT


SELECT CUSTOMER_NUMBER
FROM ORDERS
GROUP BY CUSTOMER_NUMBER
ORDER BY COUNT(*) DESC 
LIMIT 1
